dist: trusty
language: ruby
rvm:
  - 2.3.1
cache:
  bundler: true
  directories:
  - ~/.parity
before_install:
  - sudo bin/install_parity
  - gem install bundler -v 1.11.2
before_script:
  - parity --chain ~/.parity/ropsten.json --warp --password ~/.parity/pass --unlock 21e72c12878136d9349c77c1645deef121ee8926 --author 21e72c12878136d9349c77c1645deef121ee8926 daemon ~/.parity.pid --log-file ~/.parity.log
  - cat parity.log
  - sleep 5
  - parity --chain ~/.parity/ropsten.json account list
  - cat ~/.parity.log
  - bundle exec rake ethereum:node:waitforsync
  - bundle exec rake ethereum:test:setup
script:
  - bundle exec rspec --tag ~blockchain && bundle exec rspec --tag blockchain
before_cache:
  - killall parity
  - sleep 3
after_script:
  - cat /tmp/ethereum_ruby_http.log
