dist: trusty
language: ruby
rvm:
  - 2.3.1
env:
  - PARITY="1.6.5"
cache:
  bundler: true
  directories:
  - ~/.parity
before_install:
  - sudo bin/install_parity
  - gem install bundler -v 1.11.2
before_script:
  - testrpc --version
script:
  - bundle exec rspec --tag ~blockchain && bundle exec rspec --tag blockchain
before_cache:
  - killall parity
  - sleep 3
after_script:
  - cat /tmp/ethereum_ruby_http.log
